name: DevOps CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t devops-app ./app

      - name: Run container
        run: docker run -d -p 8000:8000 devops-app

      - name: Wait for app
        run: sleep 10

      - name: Show containers
        run: docker ps -a

      - name: Show logs
        run: |
          CONTAINER_ID=$(docker ps -aq)
          if [ -n "$CONTAINER_ID" ]; then
            docker logs $CONTAINER_ID
          else
            echo "No containers found"
          fi

      - name: Test app
        run: curl http://localhost:8000
